<!-- Asynchronous add() and sub()
 sub() depends on result of add()
  -->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      function add(a, b) {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            const sum = a + b;
            resolve(sum);
          }, 3000);
        });
      }

      function sub(addResult, c) {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            const diff = addResult - c;
            reject(diff);
          }, 3000);
        });
      }

      async function Operations() {
        try {
          const addResult = await add(10, 15);
          const subResult = await sub(addResult, 4);
          console.log("Result is: " + subResult);
        } catch (err) {
          console.log("Error is: " + err);
        }
      }

      Operations();
      //   when to use then and catch:
      // when a function is only handling one asynchronous call if there are more
      //   asynchrnous function calls, best to use try{} catch{}
    </script>
  </body>
</html>
